export const ActionTypes= {
    ADD_TO_CART:'ADD_TO_CART',
    REMOVE_CART:'REMOVE_CART',
    INCREASE_QUANTITY:'INCREASE_QUANTITY',
    DECREASE_QUANTITY:'DECREASE_QUANTITY',
    NUMBER_CART:'NUMBER_CART',
}